### ISSUE TITLE
Put into python module form

### ISSUE THREAD

**Issue by dacb** [yiwen26/DLSSTRP#2]
This looks like it is really coming along, but can you put it into Python module form?

**Comment by SarthakJariwala** [comment]
Working on it - Two modules (Data augmentation and CNN and CAM) done and one more to go (for Extract defect notebook)

**Comment by dacb** [comment]
Remember to keep things PEP8 compliant or somewhere define your style.  flake8 with continuous integration can help you with this.

**Comment by SarthakJariwala** [comment]
Done! The code is now PEP 8 compliant and flake8 integrated with Travis CI.
